test: add e2e provider tests
kubernetes-sigs/secrets-store-sync-controller pull request #40
Opened 2024-07-15 11:04 UTC by AlexanderStocks

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
This PR adds end-to-end (E2E) testing for the project, ensuring that the system works as expected through various scenarios.

**Which issue(s) this PR fixes**:
Fixes #2

**Special notes for your reviewer**:
Please review the added BATS tests and ensure they cover the intended scenarios correctly.
**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests

2024-07-15 19:01 UTC, nilekhc commented
/ok-to-test

2024-07-15 20:18 UTC, nilekhc requested changes

2024-07-15 20:18 UTC, nilekhc commented on Makefile
>  ## Tool Binaries
add following to invoke install targets

```shell
KIND := kind
ENVSUBST := envsubst
BATS := bats
```

This should fix current CI failures.

2024-07-15 20:20 UTC, nilekhc commented
All the review comments from https://github.com/kubernetes-sigs/secrets-store-sync-controller/pull/31 have been addressed in the version of the PR.

2024-07-18 19:00 UTC, nilekhc commented
Drop [chore: updates kubebuilder config](https://github.com/kubernetes-sigs/secrets-store-sync-controller/pull/40/commits/a89b4990063d631398ab724dfe6d950891909a37) commit. You have pulled my commit as well into this PR.

Could also add e2e tests for VAP policies we have? We want to make sure controller is not trying to do things which are restricted using VAP.

2024-07-23 16:22 UTC, nilekhc commented
> Drop [chore: updates kubebuilder config](https://github.com/kubernetes-sigs/secrets-store-sync-controller/pull/40/commits/a89b4990063d631398ab724dfe6d950891909a37) commit. You have pulled my commit as well into this PR.
> 
> Could also add e2e tests for VAP policies we have? We want to make sure controller is not trying to do things which are restricted using VAP.

VAP e2e tests will be covered by https://github.com/kubernetes-sigs/secrets-store-sync-controller/issues/47

2024-07-23 22:42 UTC, nilekhc commented
@AlexanderStocks Changes looks good. Could you squash commits into single one?

2024-07-24 21:54 UTC, nilekhc requested changes

2024-07-24 21:54 UTC, nilekhc commented on Makefile
> +ENVTEST_K8S_VERSION = 1.26.0
Is this required? Remove if not.

2024-07-26 16:40 UTC, nilekhc commented
/lgtm

/cc @aramase for approval

2024-07-26 21:47 UTC, aramase requested changes

2024-07-26 21:47 UTC, aramase commented on test/bats/README.md
> +the Secrets Store Sync Controller with the `e2e provider` as outlined as outlined [here](../../README.md#getting-started).
```suggestion
the Secrets Store Sync Controller with the `e2e provider` as outlined [here](../../README.md#getting-started).
```

2024-07-26 21:47 UTC, aramase commented on test/bats/e2e-provider.bats
> +  kubectl wait --for condition=established -n test-v1alpha1 --timeout=60s crd/secretproviderclasses.secrets-store.csi.x-k8s.io
This is already checked [here](https://github.com/kubernetes-sigs/secrets-store-sync-controller/pull/40/files#diff-395e5ad96d74d81648ec476082473348247fb32c3bbe242149b3c8b4144e7d85R11), so not required.

2024-07-26 21:47 UTC, aramase commented on test/bats/e2e-provider.bats
> +@test "[v1alpha1] deploy e2e-providerspc secretproviderclass crd" {
What is the purpose of this test? We're doing the same set of steps again [here](https://github.com/kubernetes-sigs/secrets-store-sync-controller/pull/40/files#diff-395e5ad96d74d81648ec476082473348247fb32c3bbe242149b3c8b4144e7d85R43-R48).

2024-07-26 21:47 UTC, aramase commented on test/bats/e2e-provider.bats
> +  wait_for_process $WAIT_TIME $SLEEP_TIME "$cmd"
In addition to this, need to check the data in the secret matches what we expect

2024-07-26 21:47 UTC, aramase commented on test/bats/e2e-provider.bats
> +  kubectl delete secretsync sse2esecret -n test-v1alpha1
After this step, check if the Kubernetes secret has been deleted

2024-07-26 21:47 UTC, aramase commented on test/bats/e2e-provider.bats
> +@test "Delete SecretSync and check that the secret is deleted" {
Added a comment above. I don't think we need a separate test for this. I would recommend validating every required step in `@test "[v1alpha1] deploy e2e-providerspc secretsync crd"` as a sequence.

2024-07-26 21:47 UTC, aramase commented on test/bats/helpers.bash
Need to add log collection as part of the helper, so we have logs for each test run

2024-07-29 17:03 UTC, aramase requested changes
Almost there. Just few more comments.

2024-07-30 17:07 UTC, aramase reviewed
/lgtm
/approve

2024-07-30 17:11 UTC, merged